name: Backend CI
on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.3.11
      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Restore
        run: |
          dotnet restore ./backend/src/Fundo.Applications.WebApi/Fundo.Applications.WebApi.csproj
          dotnet restore ./backend/src/Fundo.Services.Tests/Fundo.Services.Tests.csproj
      - name: Build
        run: |
          dotnet build ./backend/src/Fundo.Applications.WebApi/Fundo.Applications.WebApi.csproj --configuration Release --no-restore
          dotnet build ./backend/src/Fundo.Services.Tests/Fundo.Services.Tests.csproj --configuration Release --no-restore
      - name: Test with coverage
        run: |
          cd ./backend/src
          dotnet test --collect:"XPlat Code Coverage"
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          reportgenerator "-reports:./*/*/*/coverage.cobertura.xml" "-targetdir:Cobertura" -reporttypes:MarkdownSummary
          cat Cobertura/Summary.md >> $GITHUB_STEP_SUMMARY

      # dotnet test ./backend/src/Fundo.Services.Tests/Fundo.Services.Tests.csproj \
      #   --configuration Release --no-build --verbosity normal \
      #   /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=TestResults/coverage/ \
      #   --logger "trx;LogFileName=test_results.trx"
      # - name: Upload coverage artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage
      #     path: backend/src/Fundo.Services.Tests/TestResults/coverage/coverage.cobertura.xml
      # - name: Publish test results
      #   uses: dorny/test-reporter@v1
      #   if: always()
      #   with:
      #     name: .NET Tests
      #     path: backend/src/Fundo.Services.Tests/**/test_results.trx
      #     reporter: dotnet-trx
